### ISSUE TITLE
How is skidding going?

### ISSUE THREAD

**Issue by Tecnio** [Rammelkast/VeloxAnticheat#1]
Must be really enjoying yoinking AntiHaxerman, Medusa and Frequency 💀

**Comment by Rammelkast** [comment]
Hey man, given that a lot of my projects are open source, naturally I spend a lot of time learning from other open source projects. I remembered there being an exemption system using functional interfaces, and I like how it works. If ya want I'll note you as a contributer, don't know who exactly starting doing this first.
